version: '3.8'

services:
  postgres:
    container_name: crud-postgres
    image: crud-postgres-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crud-admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crud
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
